# Generated by Django 5.2 on 2025-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngouser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ngouser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ngouser',
            name='username',
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ngouser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
